### PR TITLE
MVP.yaml

### PR DESCRIPTION
**Pull request by twbtcclub**
circulation: "99999999999"
explorer: https://mixin.one/snapshots/384fa667-397f-3d05-a60c-70d1f61c1159
intro:
  en:
  - MetaVerse Points (MVP) is a token based on the BEP20 contract.
    The birth of MVP is mainly applied to various scenarios on the Mixin chat wallet, so that the "stable growth of BTC" in various regions can have a basic computing medium in each country.
It is convenient to promote the landing application ecology and scenarios, and it can be conveniently used as a calculation unit, and the MVP points can be used as the bargaining chip of the acceptor, so that the global synchronous development of the points system.
  zh: 
  - MVP的誕生主要是應用在Mixin聊天錢包上的各項場景，讓各地區的"穩定成長BTC"在每個國家彼此能夠有一個基本的計算基礎媒介。

  - 便於推展落地應用生態與場景，即時能夠方便作為計算單位，以MVP積分來做為承兌商的籌碼，讓全球同步發展的積分系統。

issue: 2022/11/28
name: MVP
total: "100000000000"
website: https://www.twbtc.club/mvp

### CODE REVIEW

**Comment by lyricat** [comment]
where is the yaml file?

**Comment by twbtcclub** [comment]
不好意思...剛放上去了...

**Comment by lyricat** [comment]
I still haven't seen any yaml file.

**Comment by twbtcclub** [comment]
我應該是放錯位置了...現在再放上去了...

**Comment by lyricat** [comment]
There is no yaml file in your pull request. Please confirm that before you creating a new pull request, thank you.

**Pull request closed without merging**
